import { LogDescription } from "ethers";
import { title } from "process";
import { slugify } from "zod";

{ 
    // General
    title;
    slug;
    description;
    version;
    // Clasification
    productType
    categoryId
    // Content Assets
    thumbnailFile;
    downLink;
    files jsonb; 
    licenses jsonb;

    // *** added in server *** //
    creator_id
}
loadingError



/* 
create table public.product_files(
    id uuid not null default gen_random_uuid(),
    product_id uuid not null (added from autogenerated ui)

    sort_order  (added from UI)
    provider (added from db types)
    provider_user_name (added from metadata),
    file_name (added from metadata),
    file_type (added from metadata),
    file_size (added from metadata),
    checksum (added from metadata),
    hash (added from metadata),
    provider_metadata (added from metadata),



    
    
    
    
    

    file_cache_id uuid null,
    file_cache_expires_at
    updated_at timestamp with time zone not null default now(),
    created_at timestamp with time zone not null default now(),
*/





