import type { Metadata, cookies } from "next";
import { Web3Provider } from "./providers"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WalletStatus from "@/components/wallet/NetworkInfo";
import { TronProvider } from "./TronProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
                  <AppKitStatus />
           <NetworkInfo 
            network={arbitrumSepoliaWithTokens}
            token="USDC"
          />
               <Web3Provider>
           <WalletStatus />
            {children}</Web3Provider>
      </body>
    </html>
  );
}
