/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface EscrowV1Interface extends Interface {
    getFunction(nameOrSignature: "confirmDelivery" | "confirmDelivery(bytes16)" | "contractState" | "contractState()" | "createEscrow" | "createEscrow(bytes16,address,uint16)" | "initialize" | "initialize(address,uint16,uint24)" | "openDispute" | "openDispute(bytes16)" | "orders" | "orders(bytes16)" | "owner" | "owner()" | "platformFeeBps" | "platformFeeBps()" | "platformTreasury" | "platformTreasury()" | "releaseAfterTimeout" | "releaseAfterTimeout(bytes16)" | "releaseDelay" | "releaseDelay()" | "renounceOwnership" | "renounceOwnership()" | "resolveDispute" | "resolveDispute(bytes16,bool)" | "setContractState" | "setContractState(uint8)" | "transferOwnership" | "transferOwnership(address)"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ContractStateChanged" | "ContractStateChanged(uint8)" | "EscrowCreated" | "EscrowCreated(bytes16,address,address,uint256,uint16)" | "Initialized" | "Initialized(uint64)" | "OrderDisputed" | "OrderDisputed(bytes16)" | "OrderRefunded" | "OrderRefunded(bytes16,address,uint256)" | "OrderReleased" | "OrderReleased(bytes16,address,uint256)" | "OwnershipTransferred" | "OwnershipTransferred(address,address)"): EventFragment;

    encodeFunctionData(functionFragment: 'confirmDelivery', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'confirmDelivery(bytes16)', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'contractState', values?: undefined): string;
encodeFunctionData(functionFragment: 'contractState()', values?: undefined): string;
encodeFunctionData(functionFragment: 'createEscrow', values: [BytesLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createEscrow(bytes16,address,uint16)', values: [BytesLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'initialize(address,uint16,uint24)', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'openDispute', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'openDispute(bytes16)', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'orders', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'orders(bytes16)', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner()', values?: undefined): string;
encodeFunctionData(functionFragment: 'platformFeeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'platformFeeBps()', values?: undefined): string;
encodeFunctionData(functionFragment: 'platformTreasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'platformTreasury()', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseAfterTimeout', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'releaseAfterTimeout(bytes16)', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'releaseDelay', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseDelay()', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership()', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [BytesLike, boolean]): string;
encodeFunctionData(functionFragment: 'resolveDispute(bytes16,bool)', values: [BytesLike, boolean]): string;
encodeFunctionData(functionFragment: 'setContractState', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setContractState(uint8)', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership(address)', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'confirmDelivery', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmDelivery(bytes16)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contractState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contractState()', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createEscrow(bytes16,address,uint16)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize(address,uint16,uint24)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openDispute(bytes16)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'orders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'orders(bytes16)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner()', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformFeeBps()', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformTreasury()', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseAfterTimeout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseAfterTimeout(bytes16)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseDelay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseDelay()', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership()', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute(bytes16,bool)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setContractState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setContractState(uint8)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership(address)', data: BytesLike): Result;
  }

  
    export namespace ContractStateChangedEvent {
      export type InputTuple = [newState: BigNumberish];
      export type OutputTuple = [newState: bigint];
      export interface OutputObject {newState: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowCreatedEvent {
      export type InputTuple = [orderId: BytesLike, buyer: AddressLike, seller: AddressLike, amount: BigNumberish, taxBps: BigNumberish];
      export type OutputTuple = [orderId: string, buyer: string, seller: string, amount: bigint, taxBps: bigint];
      export interface OutputObject {orderId: string, buyer: string, seller: string, amount: bigint, taxBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderDisputedEvent {
      export type InputTuple = [orderId: BytesLike];
      export type OutputTuple = [orderId: string];
      export interface OutputObject {orderId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderRefundedEvent {
      export type InputTuple = [orderId: BytesLike, buyer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [orderId: string, buyer: string, amount: bigint];
      export interface OutputObject {orderId: string, buyer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderReleasedEvent {
      export type InputTuple = [orderId: BytesLike, seller: AddressLike, sellerAmount: BigNumberish];
      export type OutputTuple = [orderId: string, seller: string, sellerAmount: bigint];
      export interface OutputObject {orderId: string, seller: string, sellerAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EscrowV1 extends BaseContract {
    
    connect(runner?: ContractRunner | null): EscrowV1;
    waitForDeployment(): Promise<this>;

    interface: EscrowV1Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    confirmDelivery: TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >
    
    
    "confirmDelivery(bytes16)": TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    contractState: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    
    
    "contractState()": TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    createEscrow: TypedContractMethod<
      [orderId: BytesLike, seller: AddressLike, taxBps: BigNumberish, ],
      [void],
      'payable'
    >
    
    
    "createEscrow(bytes16,address,uint16)": TypedContractMethod<
      [orderId: BytesLike, seller: AddressLike, taxBps: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    initialize: TypedContractMethod<
      [_platformTreasury: AddressLike, _feeBps: BigNumberish, _releaseDelay: BigNumberish, ],
      [void],
      'nonpayable'
    >
    
    
    "initialize(address,uint16,uint24)": TypedContractMethod<
      [_platformTreasury: AddressLike, _feeBps: BigNumberish, _releaseDelay: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    openDispute: TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >
    
    
    "openDispute(bytes16)": TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    orders: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, bigint, bigint] & {buyer: string, seller: string, amount: bigint, taxBps: bigint, createdAt: bigint, state: bigint }],
      'view'
    >
    
    
    "orders(bytes16)": TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, bigint, bigint] & {buyer: string, seller: string, amount: bigint, taxBps: bigint, createdAt: bigint, state: bigint }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    
    
    "owner()": TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    platformFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    
    
    "platformFeeBps()": TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    platformTreasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    
    
    "platformTreasury()": TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    releaseAfterTimeout: TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >
    
    
    "releaseAfterTimeout(bytes16)": TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    releaseDelay: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    
    
    "releaseDelay()": TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    
    
    "renounceOwnership()": TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    resolveDispute: TypedContractMethod<
      [orderId: BytesLike, refundBuyer: boolean, ],
      [void],
      'nonpayable'
    >
    
    
    "resolveDispute(bytes16,bool)": TypedContractMethod<
      [orderId: BytesLike, refundBuyer: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setContractState: TypedContractMethod<
      [newState: BigNumberish, ],
      [void],
      'nonpayable'
    >
    
    
    "setContractState(uint8)": TypedContractMethod<
      [newState: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    
    
    "transferOwnership(address)": TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'confirmDelivery'): TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirmDelivery(bytes16)'): TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'contractState'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'contractState()'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createEscrow'): TypedContractMethod<
      [orderId: BytesLike, seller: AddressLike, taxBps: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'createEscrow(bytes16,address,uint16)'): TypedContractMethod<
      [orderId: BytesLike, seller: AddressLike, taxBps: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_platformTreasury: AddressLike, _feeBps: BigNumberish, _releaseDelay: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initialize(address,uint16,uint24)'): TypedContractMethod<
      [_platformTreasury: AddressLike, _feeBps: BigNumberish, _releaseDelay: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'openDispute'): TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'openDispute(bytes16)'): TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'orders'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, bigint, bigint] & {buyer: string, seller: string, amount: bigint, taxBps: bigint, createdAt: bigint, state: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'orders(bytes16)'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, bigint, bigint] & {buyer: string, seller: string, amount: bigint, taxBps: bigint, createdAt: bigint, state: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner()'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'platformFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'platformFeeBps()'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'platformTreasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'platformTreasury()'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'releaseAfterTimeout'): TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseAfterTimeout(bytes16)'): TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseDelay'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'releaseDelay()'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership()'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [orderId: BytesLike, refundBuyer: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute(bytes16,bool)'): TypedContractMethod<
      [orderId: BytesLike, refundBuyer: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setContractState'): TypedContractMethod<
      [newState: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setContractState(uint8)'): TypedContractMethod<
      [newState: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership(address)'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ContractStateChanged'): TypedContractEvent<ContractStateChangedEvent.InputTuple, ContractStateChangedEvent.OutputTuple, ContractStateChangedEvent.OutputObject>;
getEvent(key: 'ContractStateChanged(uint8)'): TypedContractEvent<ContractStateChanged_uint8_Event.InputTuple, ContractStateChanged_uint8_Event.OutputTuple, ContractStateChanged_uint8_Event.OutputObject>;
getEvent(key: 'EscrowCreated'): TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
getEvent(key: 'EscrowCreated(bytes16,address,address,uint256,uint16)'): TypedContractEvent<EscrowCreated_bytes16_address_address_uint256_uint16_Event.InputTuple, EscrowCreated_bytes16_address_address_uint256_uint16_Event.OutputTuple, EscrowCreated_bytes16_address_address_uint256_uint16_Event.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'Initialized(uint64)'): TypedContractEvent<Initialized_uint64_Event.InputTuple, Initialized_uint64_Event.OutputTuple, Initialized_uint64_Event.OutputObject>;
getEvent(key: 'OrderDisputed'): TypedContractEvent<OrderDisputedEvent.InputTuple, OrderDisputedEvent.OutputTuple, OrderDisputedEvent.OutputObject>;
getEvent(key: 'OrderDisputed(bytes16)'): TypedContractEvent<OrderDisputed_bytes16_Event.InputTuple, OrderDisputed_bytes16_Event.OutputTuple, OrderDisputed_bytes16_Event.OutputObject>;
getEvent(key: 'OrderRefunded'): TypedContractEvent<OrderRefundedEvent.InputTuple, OrderRefundedEvent.OutputTuple, OrderRefundedEvent.OutputObject>;
getEvent(key: 'OrderRefunded(bytes16,address,uint256)'): TypedContractEvent<OrderRefunded_bytes16_address_uint256_Event.InputTuple, OrderRefunded_bytes16_address_uint256_Event.OutputTuple, OrderRefunded_bytes16_address_uint256_Event.OutputObject>;
getEvent(key: 'OrderReleased'): TypedContractEvent<OrderReleasedEvent.InputTuple, OrderReleasedEvent.OutputTuple, OrderReleasedEvent.OutputObject>;
getEvent(key: 'OrderReleased(bytes16,address,uint256)'): TypedContractEvent<OrderReleased_bytes16_address_uint256_Event.InputTuple, OrderReleased_bytes16_address_uint256_Event.OutputTuple, OrderReleased_bytes16_address_uint256_Event.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred(address,address)'): TypedContractEvent<OwnershipTransferred_address_address_Event.InputTuple, OwnershipTransferred_address_address_Event.OutputTuple, OwnershipTransferred_address_address_Event.OutputObject>;

    filters: {
      
      'ContractStateChanged(uint8)': TypedContractEvent<ContractStateChangedEvent.InputTuple, ContractStateChangedEvent.OutputTuple, ContractStateChangedEvent.OutputObject>;
      ContractStateChanged: TypedContractEvent<ContractStateChangedEvent.InputTuple, ContractStateChangedEvent.OutputTuple, ContractStateChangedEvent.OutputObject>;
    

      'EscrowCreated(bytes16,address,address,uint256,uint16)': TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
      EscrowCreated: TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'OrderDisputed(bytes16)': TypedContractEvent<OrderDisputedEvent.InputTuple, OrderDisputedEvent.OutputTuple, OrderDisputedEvent.OutputObject>;
      OrderDisputed: TypedContractEvent<OrderDisputedEvent.InputTuple, OrderDisputedEvent.OutputTuple, OrderDisputedEvent.OutputObject>;
    

      'OrderRefunded(bytes16,address,uint256)': TypedContractEvent<OrderRefundedEvent.InputTuple, OrderRefundedEvent.OutputTuple, OrderRefundedEvent.OutputObject>;
      OrderRefunded: TypedContractEvent<OrderRefundedEvent.InputTuple, OrderRefundedEvent.OutputTuple, OrderRefundedEvent.OutputObject>;
    

      'OrderReleased(bytes16,address,uint256)': TypedContractEvent<OrderReleasedEvent.InputTuple, OrderReleasedEvent.OutputTuple, OrderReleasedEvent.OutputObject>;
      OrderReleased: TypedContractEvent<OrderReleasedEvent.InputTuple, OrderReleasedEvent.OutputTuple, OrderReleasedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }