/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ITransparentUpgradeableProxyInterface extends Interface {
    getFunction(nameOrSignature: "upgradeToAndCall" | "upgradeToAndCall(address,bytes)"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AdminChanged" | "AdminChanged(address,address)" | "BeaconUpgraded" | "BeaconUpgraded(address)" | "Upgraded" | "Upgraded(address)"): EventFragment;

    encodeFunctionData(functionFragment: 'upgradeToAndCall', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'upgradeToAndCall(address,bytes)', values: [AddressLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'upgradeToAndCall', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeToAndCall(address,bytes)', data: BytesLike): Result;
  }

  
    export namespace AdminChangedEvent {
      export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
      export type OutputTuple = [previousAdmin: string, newAdmin: string];
      export interface OutputObject {previousAdmin: string, newAdmin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BeaconUpgradedEvent {
      export type InputTuple = [beacon: AddressLike];
      export type OutputTuple = [beacon: string];
      export interface OutputObject {beacon: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ITransparentUpgradeableProxy extends BaseContract {
    
    connect(runner?: ContractRunner | null): ITransparentUpgradeableProxy;
    waitForDeployment(): Promise<this>;

    interface: ITransparentUpgradeableProxyInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    
    
    "upgradeToAndCall(address,bytes)": TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'upgradeToAndCall'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'upgradeToAndCall(address,bytes)'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;

    getEvent(key: 'AdminChanged'): TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
getEvent(key: 'AdminChanged(address,address)'): TypedContractEvent<AdminChanged_address_address_Event.InputTuple, AdminChanged_address_address_Event.OutputTuple, AdminChanged_address_address_Event.OutputObject>;
getEvent(key: 'BeaconUpgraded'): TypedContractEvent<BeaconUpgradedEvent.InputTuple, BeaconUpgradedEvent.OutputTuple, BeaconUpgradedEvent.OutputObject>;
getEvent(key: 'BeaconUpgraded(address)'): TypedContractEvent<BeaconUpgraded_address_Event.InputTuple, BeaconUpgraded_address_Event.OutputTuple, BeaconUpgraded_address_Event.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
getEvent(key: 'Upgraded(address)'): TypedContractEvent<Upgraded_address_Event.InputTuple, Upgraded_address_Event.OutputTuple, Upgraded_address_Event.OutputObject>;

    filters: {
      
      'AdminChanged(address,address)': TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
      AdminChanged: TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
    

      'BeaconUpgraded(address)': TypedContractEvent<BeaconUpgradedEvent.InputTuple, BeaconUpgradedEvent.OutputTuple, BeaconUpgradedEvent.OutputObject>;
      BeaconUpgraded: TypedContractEvent<BeaconUpgradedEvent.InputTuple, BeaconUpgradedEvent.OutputTuple, BeaconUpgradedEvent.OutputObject>;
    

      'Upgraded(address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    
    };
  }