// lib/db/licenses/types/RegionEnumIcons.ts

import { RegionEnum } from "./RegionEnum";

// Use Record to map RegionEnum values to string (representing flag classes)
export interface RegionEnumIcons extends Partial<Record<RegionEnum, string>> {}

export const regionIcons: RegionEnumIcons = {
  [RegionEnum.Global]: "",

  [RegionEnum.Afghanistan]: "fi fi-af",
  [RegionEnum.Albania]: "fi fi-al",
  [RegionEnum.Algeria]: "fi fi-dz",
  [RegionEnum.Andorra]: "fi fi-ad",
  [RegionEnum.Angola]: "fi fi-ao",
  [RegionEnum.AntiguaAndBarbuda]: "fi fi-ag",
  [RegionEnum.Argentina]: "fi fi-ar",
  [RegionEnum.Armenia]: "fi fi-am",
  [RegionEnum.Australia]: "fi fi-au",
  [RegionEnum.Austria]: "fi fi-at",
  [RegionEnum.Azerbaijan]: "fi fi-az",

  [RegionEnum.Bahamas]: "fi fi-bs",
  [RegionEnum.Bahrain]: "fi fi-bh",
  [RegionEnum.Bangladesh]: "fi fi-bd",
  [RegionEnum.Barbados]: "fi fi-bb",
  [RegionEnum.Belarus]: "fi fi-by",
  [RegionEnum.Belgium]: "fi fi-be",
  [RegionEnum.Belize]: "fi fi-bz",
  [RegionEnum.Benin]: "fi fi-bj",
  [RegionEnum.Bhutan]: "fi fi-bt",
  [RegionEnum.Bolivia]: "fi fi-bo",
  [RegionEnum.BosniaAndHerzegovina]: "fi fi-ba",
  [RegionEnum.Botswana]: "fi fi-bw",
  [RegionEnum.Brazil]: "fi fi-br",
  [RegionEnum.Brunei]: "fi fi-bn",
  [RegionEnum.Bulgaria]: "fi fi-bg",
  [RegionEnum.BurkinaFaso]: "fi fi-bf",
  [RegionEnum.Burundi]: "fi fi-bi",

  [RegionEnum.CaboVerde]: "fi fi-cv",
  [RegionEnum.Cambodia]: "fi fi-kh",
  [RegionEnum.Cameroon]: "fi fi-cm",
  [RegionEnum.Canada]: "fi fi-ca",
  [RegionEnum.CentralAfricanRepublic]: "fi fi-cf",
  [RegionEnum.Chad]: "fi fi-td",
  [RegionEnum.Chile]: "fi fi-cl",
  [RegionEnum.China]: "fi fi-cn",
  [RegionEnum.Colombia]: "fi fi-co",
  [RegionEnum.Comoros]: "fi fi-km",
  [RegionEnum.CongoBrazzaville]: "fi fi-cg",
  [RegionEnum.CongoKinshasa]: "fi fi-cd",
  [RegionEnum.CostaRica]: "fi fi-cr",
  [RegionEnum.Croatia]: "fi fi-hr",
  [RegionEnum.Cuba]: "fi fi-cu",
  [RegionEnum.Cyprus]: "fi fi-cy",
  [RegionEnum.CzechRepublic]: "fi fi-cz",

  [RegionEnum.Denmark]: "fi fi-dk",
  [RegionEnum.Djibouti]: "fi fi-dj",
  [RegionEnum.Dominica]: "fi fi-dm",
  [RegionEnum.DominicanRepublic]: "fi fi-do",

  [RegionEnum.Ecuador]: "fi fi-ec",
  [RegionEnum.Egypt]: "fi fi-eg",
  [RegionEnum.ElSalvador]: "fi fi-sv",
  [RegionEnum.EquatorialGuinea]: "fi fi-gq",
  [RegionEnum.Eritrea]: "fi fi-er",
  [RegionEnum.Estonia]: "fi fi-ee",
  [RegionEnum.Eswatini]: "fi fi-sz",
  [RegionEnum.Ethiopia]: "fi fi-et",

  [RegionEnum.Fiji]: "fi fi-fj",
  [RegionEnum.Finland]: "fi fi-fi",
  [RegionEnum.France]: "fi fi-fr",

  [RegionEnum.Gabon]: "fi fi-ga",
  [RegionEnum.Gambia]: "fi fi-gm",
  [RegionEnum.Georgia]: "fi fi-ge",
  [RegionEnum.Germany]: "fi fi-de",
  [RegionEnum.Ghana]: "fi fi-gh",
  [RegionEnum.Greece]: "fi fi-gr",
  [RegionEnum.Grenada]: "fi fi-gd",
  [RegionEnum.Guatemala]: "fi fi-gt",
  [RegionEnum.Guinea]: "fi fi-gn",
  [RegionEnum.GuineaBissau]: "fi fi-gw",
  [RegionEnum.Guyana]: "fi fi-gy",

  [RegionEnum.Haiti]: "fi fi-ht",
  [RegionEnum.Honduras]: "fi fi-hn",
  [RegionEnum.Hungary]: "fi fi-hu",

  [RegionEnum.Iceland]: "fi fi-is",
  [RegionEnum.India]: "fi fi-in",
  [RegionEnum.Indonesia]: "fi fi-id",
  [RegionEnum.Iran]: "fi fi-ir",
  [RegionEnum.Iraq]: "fi fi-iq",
  [RegionEnum.Ireland]: "fi fi-ie",
  [RegionEnum.Israel]: "fi fi-il",
  [RegionEnum.Italy]: "fi fi-it",

  [RegionEnum.Jamaica]: "fi fi-jm",
  [RegionEnum.Japan]: "fi fi-jp",
  [RegionEnum.Jordan]: "fi fi-jo",

  [RegionEnum.Kazakhstan]: "fi fi-kz",
  [RegionEnum.Kenya]: "fi fi-ke",
  [RegionEnum.Kiribati]: "fi fi-ki",
  [RegionEnum.KoreaNorth]: "fi fi-kp",
  [RegionEnum.KoreaSouth]: "fi fi-kr",
  [RegionEnum.Kuwait]: "fi fi-kw",
  [RegionEnum.Kyrgyzstan]: "fi fi-kg",

  [RegionEnum.Laos]: "fi fi-la",
  [RegionEnum.Latvia]: "fi fi-lv",
  [RegionEnum.Lebanon]: "fi fi-lb",
  [RegionEnum.Lesotho]: "fi fi-ls",
  [RegionEnum.Liberia]: "fi fi-lr",
  [RegionEnum.Libya]: "fi fi-ly",
  [RegionEnum.Liechtenstein]: "fi fi-li",
  [RegionEnum.Lithuania]: "fi fi-lt",
  [RegionEnum.Luxembourg]: "fi fi-lu",

  [RegionEnum.Madagascar]: "fi fi-mg",
  [RegionEnum.Malawi]: "fi fi-mw",
  [RegionEnum.Malaysia]: "fi fi-my",
  [RegionEnum.Maldives]: "fi fi-mv",
  [RegionEnum.Mali]: "fi fi-ml",
  [RegionEnum.Malta]: "fi fi-mt",
  [RegionEnum.MarshallIslands]: "fi fi-mh",
  [RegionEnum.Mauritania]: "fi fi-mr",
  [RegionEnum.Mauritius]: "fi fi-mu",
  [RegionEnum.Mexico]: "fi fi-mx",
  [RegionEnum.Micronesia]: "fi fi-fm",
  [RegionEnum.Moldova]: "fi fi-md",
  [RegionEnum.Monaco]: "fi fi-mc",
  [RegionEnum.Mongolia]: "fi fi-mn",
  [RegionEnum.Montenegro]: "fi fi-me",
  [RegionEnum.Morocco]: "fi fi-ma",
  [RegionEnum.Mozambique]: "fi fi-mz",
  [RegionEnum.Myanmar]: "fi fi-mm",

  [RegionEnum.Namibia]: "fi fi-na",
  [RegionEnum.Nauru]: "fi fi-nr",
  [RegionEnum.Nepal]: "fi fi-np",
  [RegionEnum.Netherlands]: "fi fi-nl",
  [RegionEnum.NewZealand]: "fi fi-nz",
  [RegionEnum.Nicaragua]: "fi fi-ni",
  [RegionEnum.Niger]: "fi fi-ne",
  [RegionEnum.Nigeria]: "fi fi-ng",
  [RegionEnum.NorthMacedonia]: "fi fi-mk",
  [RegionEnum.Norway]: "fi fi-no",

  [RegionEnum.Oman]: "fi fi-om",

  [RegionEnum.Pakistan]: "fi fi-pk",
  [RegionEnum.Palau]: "fi fi-pw",
  [RegionEnum.Panama]: "fi fi-pa",
  [RegionEnum.PapuaNewGuinea]: "fi fi-pg",
  [RegionEnum.Paraguay]: "fi fi-py",
  [RegionEnum.Peru]: "fi fi-pe",
  [RegionEnum.Philippines]: "fi fi-ph",
  [RegionEnum.Poland]: "fi fi-pl",
  [RegionEnum.Portugal]: "fi fi-pt",
  [RegionEnum.Qatar]: "fi fi-qa",

  [RegionEnum.Romania]: "fi fi-ro",
  [RegionEnum.Russia]: "fi fi-ru",
  [RegionEnum.Rwanda]: "fi fi-rw",

  [RegionEnum.SaudiArabia]: "fi fi-sa",
  [RegionEnum.Senegal]: "fi fi-sn",
  [RegionEnum.Serbia]: "fi fi-rs",
  [RegionEnum.Seychelles]: "fi fi-sc",
  [RegionEnum.SierraLeone]: "fi fi-sl",
  [RegionEnum.Singapore]: "fi fi-sg",
  [RegionEnum.Slovakia]: "fi fi-sk",
  [RegionEnum.Slovenia]: "fi fi-si",
  [RegionEnum.SolomonIslands]: "fi fi-sb",
  [RegionEnum.Somalia]: "fi fi-so",
  [RegionEnum.SouthAfrica]: "fi fi-za",
  [RegionEnum.SouthSudan]: "fi fi-ss",
  [RegionEnum.Spain]: "fi fi-es",
  [RegionEnum.SriLanka]: "fi fi-lk",
  [RegionEnum.Sudan]: "fi fi-sd",
  [RegionEnum.Suriname]: "fi fi-sr",
  [RegionEnum.Sweden]: "fi fi-se",
  [RegionEnum.Switzerland]: "fi fi-ch",
  [RegionEnum.Syria]: "fi fi-sy",

  [RegionEnum.Taiwan]: "fi fi-tw",
  [RegionEnum.Tajikistan]: "fi fi-tj",
  [RegionEnum.Tanzania]: "fi fi-tz",
  [RegionEnum.Thailand]: "fi fi-th",
  [RegionEnum.TimorLeste]: "fi fi-tl",
  [RegionEnum.Togo]: "fi fi-tg",
  [RegionEnum.Tonga]: "fi fi-to",
  [RegionEnum.TrinidadAndTobago]: "fi fi-tt",
  [RegionEnum.Tunisia]: "fi fi-tn",
  [RegionEnum.Turkey]: "fi fi-tr",
  [RegionEnum.Turkmenistan]: "fi fi-tm",
  [RegionEnum.Tuvalu]: "fi fi-tv",

  [RegionEnum.Uganda]: "fi fi-ug",
  [RegionEnum.Ukraine]: "fi fi-ua",
  [RegionEnum.UnitedArabEmirates]: "fi fi-ae",
  [RegionEnum.UnitedKingdom]: "fi fi-gb",
  [RegionEnum.UnitedStates]: "fi fi-us",
  [RegionEnum.Uruguay]: "fi fi-uy",
  [RegionEnum.Uzbekistan]: "fi fi-uz",

  [RegionEnum.Vanuatu]: "fi fi-vu",
  [RegionEnum.VaticanCity]: "fi fi-va",
  [RegionEnum.Venezuela]: "fi fi-ve",
  [RegionEnum.Vietnam]: "fi fi-vn",

  [RegionEnum.Yemen]: "fi fi-ye",
  [RegionEnum.Zambia]: "fi fi-zm",
  [RegionEnum.Zimbabwe]: "fi fi-zw",
};
